config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/about'
  get 'pages/about'

  namespace :admin do
    resources :orders
    resources :products do
      resources :stocks
    end
    resources :categories
  end
  devise_for :admins

  authenticated :admin do
    root to: "admin#index", as: :admin_root
  end

  get "admin" => "admin#index"
  get "cart" => "carts#show"
  post "/checkouts" => "checkouts#create"
  get '/success', to: 'checkouts#success'
  get '/cancel', to: 'checkouts#cancel'
  post "webhooks" => "webhooks#stripe"
  get '/search', to: 'products#search', as: 'search_products'
  get '/sobre', to: 'static_pages#about', as: 'about'

  resources :categories, only: [:show]
  resources :products, only: [:show, :index]

  root "home#index"
end

app/models/order.rb
class Order < ApplicationRecord
   has_many :order_products
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController
  before_action :set_admin_order, only: %i[ show edit update destroy ]

  # GET /admin/orders or /admin/orders.json
  def index
    @not_fulfilled_orders = Order.where(fullfiled: false).order(created_at: :asc)
    @fulfilled_orders = Order.where(fullfiled: true).order(created_at: :asc)
    # @admin_orders = Order.where(fullfiled: false).order(created_at: :asc)
  end

  # GET /admin/orders/1 or /admin/orders/1.json
  def show
  end

  # GET /admin/orders/new
  def new
    @admin_order = Order.new
  end

  # GET /admin/orders/1/edit
  def edit
  end

  # POST /admin/orders or /admin/orders.json
  def create
    @admin_order = Order.new(admin_order_params)

    respond_to do |format|
      if @admin_order.save
        format.html { redirect_to admin_order_url(@admin_order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @admin_order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/orders/1 or /admin/orders/1.json
  def update
    respond_to do |format|
      if @admin_order.update(admin_order_params)
        format.html { redirect_to admin_order_url(@admin_order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @admin_order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/orders/1 or /admin/orders/1.json
  def destroy
    @admin_order.destroy!

    respond_to do |format|
      format.html { redirect_to admin_orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_order
      @admin_order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_order_params
      params.require(:order).permit(:customer_email, :fullfiled, :total, :address)
    end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/_form.html.erb
<%= form_with(model: [:admin, admin_order], class: "contents") do |form| %>
  <% if admin_order.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(admin_order.errors.count, "error") %> proibiram que esta ordem fosse salva:</h2>

      <ul>
        <% admin_order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :customer_email, class: "block font-medium text-gray-800" %>
    <%= form.text_field :customer_email, class: "block shadow-sm rounded-md border border-gray-300 outline-none px-3 py-2 mt-1 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :fulfilled, class: "block font-medium text-gray-800" %>
    <%= form.check_box :fulfilled, class: "form-checkbox h-5 w-5 text-blue-600" %>
  </div>

  <div class="my-5">
    <%= form.label :total, class: "block font-medium text-gray-800" %>
    <%= form.number_field :total, class: "block shadow-sm rounded-md border border-gray-300 outline-none px-3 py-2 mt-1 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :address, class: "block font-medium text-gray-800" %>
    <%= form.text_field :address, class: "block shadow-sm rounded-md border border-gray-300 outline-none px-3 py-2 mt-1 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :delivery_date, class: "block font-medium text-gray-800" %>
    <%= form.date_field :delivery_date, class: "block shadow-sm rounded-md border border-gray-300 outline-none px-3 py-2 mt-1 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit "Salvar Ordem", class: "inline-block px-6 py-3 text-white rounded-lg bg-blue-600 font-medium hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50" %>
  </div>
<% end %>

app/views/admin/orders/_order.html.erb
<div id="<%= dom_id(order) %>">
  <div class="my-5">
    <strong class="block font-medium mb-1">E-mail do Cliente:</strong>
    <%= order.customer_email %>
  </div>

  <div class="my-5">
    <strong class="block font-medium mb-1">Fulfillment:</strong>
    <%= order.fullfiled ? "Sim" : "Não" %>
  </div>

  <div class="my-5">
    <strong class="block font-medium mb-1">Total:</strong>
    <%= number_to_currency(order.total, unit: 'R$', separator: ',', delimiter: '.') %>
  </div>

  <div class="my-5">
    <strong class="block font-medium mb-1">Endereço de Entrega:</strong>
    <%= order.address %>
  </div>

  <% if order.order_products.any? %>
    <div class="my-5">
      <strong class="block font-medium mb-1">Produtos:</strong>
      <ul class="list-disc list-inside">
        <% order.order_products.each do |op| %>
          <li><%= "#{op.product.name} - #{op.size} - Quantidade: #{op.quantity}" %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if action_name != "show" %>
    <div class="flex mt-6">
      <%= link_to "Mostrar este pedido", [:admin, order], class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium mr-2" %>
      <%= link_to "Editar este pedido", edit_admin_order_path(order), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    </div>
    <hr class="mt-6">
  <% end %>
</div>

app/views/admin/orders/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editar Pedido</h1>

  <%= render "form", admin_order: @admin_order %>

  <div class="mt-6">
    <%= link_to "Mostrar este Pedido", [:admin, @admin_order], class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium ml-2" %>
    <%= link_to "Voltar para Pedidos", admin_orders_path, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium ml-2" %>
  </div>
</div>

app/views/admin/orders/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center mb-6">
    <h1 class="font-bold text-4xl">Pedidos</h1>
    <%= link_to "Novo Pedido", new_admin_order_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div class="mb-8">
    <h2 class="text-2xl mb-2 font-medium">Pedidos Pendentes</h2>
    <div class="overflow-x-auto sm:mx-0.5 lg:mx-0.5">
      <table class="min-w-full overflow-x-scroll bg-white shadow-md rounded-lg">
        <thead class="bg-gray-200">
          <tr>
            <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">ID do Pedido</th>
            <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">E-mail do Cliente</th>
            <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">Endereço</th>
            <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">Total</th>
          </tr>
        </thead>
        <tbody class="text-gray-700">
          <% @not_fulfilled_orders.each do |order| %>
            <tr class="border-b">
              <td class="px-6 py-4 whitespace-nowrap"><%= link_to order.id, [:admin, order], class: 'underline' %></td>
              <td class="px-6 py-4 whitespace-nowrap"><%= order.customer_email %></td>
              <td class="px-6 py-4 whitespace-nowrap"><%= order.address %></td>
              <td class="px-6 py-4 whitespace-nowrap">R$ <%= number_to_currency(order.total, unit: '', separator: ',', delimiter: '.') %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div>
    <h2 class="text-2xl mb-2 font-medium">Pedidos Atendidos</h2>
    <div class="overflow-x-auto sm:mx-0.5 lg:mx-0.5">
      <table class="min-w-full overflow-x-scroll bg-white shadow-md rounded-lg">
        <thead class="bg-gray-200">
          <tr>
            <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">ID do Pedido</th>
            <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">E-mail do Cliente</th>
            <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">Endereço</th>
            <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">Total</th>
          </tr>
        </thead>
        <tbody class="text-gray-700">
          <% @fulfilled_orders.each do |order| %>
            <tr class="border-b">
              <td class="px-6 py-4 whitespace-nowrap"><%= link_to order.id, [:admin, order], class: 'underline' %></td>
              <td class="px-6 py-4 whitespace-nowrap"><%= order.customer_email %></td>
              <td class="px-6 py-4 whitespace-nowrap"><%= order.address %></td>
              <td class="px-6 py-4 whitespace-nowrap">R$ <%= number_to_currency(order.total, unit: '', separator: ',', delimiter: '.') %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/orders/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Novo Pedido</h1>

  <%= render "form", admin_order: @admin_order %>

  <%= link_to "Voltar para Pedidos", admin_orders_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/orders/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @admin_order %>

    <%= link_to "Editar este pedido", edit_admin_order_path(@admin_order), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Voltar para pedidos", admin_orders_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Excluir este pedido", admin_order_path(@admin_order), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>