config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/about'
  get 'pages/about'

  namespace :admin do
    resources :orders
    resources :products do
      resources :stocks
    end
    resources :categories
  end
  devise_for :admins

  authenticated :admin do
    root to: "admin#index", as: :admin_root
  end

  get "admin" => "admin#index"
  get "cart" => "carts#show"
  post "/checkouts" => "checkouts#create"
  get '/success', to: 'checkouts#success'
  get '/cancel', to: 'checkouts#cancel'
  post "webhooks" => "webhooks#stripe"
  get '/search', to: 'products#search', as: 'search_products'
  get '/sobre', to: 'static_pages#about', as: 'about'

  resources :categories, only: [:show]
  resources :products, only: [:show, :index]

  root "home#index"
end

app/views/shared/_footer.html.erb
<footer class="bg-red-600 text-white">
    <div class="max-w-6xl mx-auto px-4 py-10 md:py-20">
        <div class="xl:grid xl:grid-cols-3 xl:gap-8">
            <!-- About Section -->
            <div class="space-y-8 xl:col-span-1">
                <h3 class="text-sm font-semibold text-yellow-300 tracking-wider uppercase">
                    Sobre o Ecommerce
                </h3>
                <p class="text-white leading-6">
                    Lanches deliciosos para você
                </p>
            </div>
            <!-- Links Section -->
            <div class="mt-12 grid grid-cols-2 gap-8 xl:mt-0 xl:col-span-1">
                <div>
                    <h3 class="text-sm font-semibold text-yellow-300 tracking-wider uppercase">
                        Links
                    </h3>
                    <ul class="mt-4 space-y-4">
                        <li>
                            <%= link_to "Home", root_path, class:"text-base leading-6 text-white hover:text-yellow-200"%>
                        </li>
                        <!-- Add more links here if needed -->
                    </ul>
                </div>
            </div>
            <!-- Contact Section -->
            <div class="mt-8 mb-8 xl:mt-0 xl:col-span-1">
                <div>
                    <h3 class="text-sm font-semibold tracking-wider uppercase text-yellow-300">
                        Contato
                    </h3>
                    <ul class="mt-4 space-y-4">
                        <li>
                            <p class="text-base leading-6 text-white">
                                Amaral <br>
                               
                            </p>
                        </li>
                        <li>
                            <p class="text-base leading-6 text-white">
                                 Telefone: (31) 98916-2848
                            </p>
                        </li>
                        <li>
                            <p class="text-base leading-6 text-white">
                                
                            </p>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="border-t border-yellow-500 mt-8">
            <div class="max-w-6xl mx-auto px-4 py-6 md:flex md:items-center md:justify-between">
                <p class="text-base leading-6 text-yellow-200 md:order-1">
                    © <%= Time.now.year %> Amaral burger, Inc. Todos os direitos reservados.
                </p>
            </div>
        </div>
    </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="fixed w-full top-0 bg-yellow-300 z-10 shadow-md">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-16">
      <div class="flex items-center">
        <!-- Links de navegação -->
        <div class="flex space-x-6">
          <%= link_to 'Início', root_path, class: 'text-gray-900 hover:text-red-700' %>
          <%= link_to 'Sobre', about_path, class: 'text-gray-900 hover:text-red-700' %>

          <!-- Botões de Categorias -->
          <div class="flex space-x-4">
            <% Category.all.each do |category| %>
              <%= link_to category_path(category), class: 'text-gray-900 hover:text-red-700 focus:outline-none flex items-center' do %>
                <%= category.name %>
              <% end %>
            <% end %>
          </div>
          <!-- Fim dos Botões de Categorias -->
        </div>
      </div>

      <!-- Logo -->
      <div class="hidden lg:flex items-center justify-center">
        <%= link_to root_path do %>
          <%= image_tag 'amaral.png', alt: 'Logo do Restaurante', class: 'h-12' %>
        <% end %>
      </div>

      <div class="flex items-center">
        <!-- Carrinho -->
        <%= link_to cart_path, class: 'text-gray-900 hover:text-red-700 ml-6' do %>
          <%= icon 'fa-solid', 'shopping-cart' %>
        <% end %>
      </div>
    </div>
  </div>
</nav>